### ISSUE TITLE
USB keyboard problems

### ISSUE THREAD

**Issue by eshazen** [RC2014Z80/picoterm#1]
Just assembled my PicoTerm.  I have two USB keyboards.  One doesn't work at all, the other works only intermittently (if I press RUN) a few times and reset the RC2014 each time it will sometimes recognize the keyboard.

I'd be happy to help debug, as without a keyboard it isn't very useful :).
Is there any way to get a console or such on the pi (I don't have much experience with the pico).

**Comment by RFC2795** [comment]
Hi Eric,
I know some keyboards work fine, and some don't work at all, and I'm trying to compile a list of good/bad ones, and hopefully identify a trend or something. However, I haven't come across any which only work intermittently.

Note that if you have something else (eg FTDI cable, or Wifi module) connected to the same Rx pin on the RC2014, you will get issues where one or both inputs are ignored. So, I'm not sure if maybe that's whats going on?  Might possibly be the USB OTG adapter?

Can you let us know what the make and model of the two keyboards are that you've tried.

The Pi Pico doesn't have a console per say. It is just a microcontroller, so it isn't running any operating system
