### ISSUE TITLE
Crash when changing colours ...

### ISSUE THREAD

**Issue by spock64** [RC2014Z80/picoterm#14]
Hi,

So I looked at why the pico crashes after changing the colours a few times. This appears to be due to running out of memory as the font memory is not released when rebuilding the font each time the colour changes ...

This (in main.c) fixes it ...

```
...
void build_font() {
    uint16_t colors[16];

    // Free up previous font ...
    if(font_raw_pixels)
    {
        free(font_raw_pixels);
    }
...

```

I will train up on how to do pull requests!

**Comment by mchobby** [comment]
This indeed save the problem.
Many thanks... this is welcome for the coming NuPetScii
