### ISSUE TITLE
80 Columns version shows only 79 Columns

### ISSUE THREAD

**Issue by abaffa** [RC2014Z80/picoterm#16]
Hi, 
 I've been adding some escapes and few stuff to 80 columns version and I noticed that it's showing only 79 chars. It occurs 'cos 640 / 8 = 80 but #define COUNT MIN(vga_mode.width/(FRAGMENT_WORDS*2)-1, 80) returns 79.

so it's reading columns from 0-78 >> for (int i = 0; i < COUNT; i++) 

But also I tried to add the last column and the horizontal sync is stretched to beam only 79 chars during the scanline process. I realized it's because of the beginning_of_line and ending segments. I tried a FRAGMENT_WORDS of 3 using ubuntu_mono8 and it shows a "progress"  (as it's using less pixels to the scanline) but it's far from be a solution.

Could you please check it or maybe help me to fix it? 

best,
Augusto Baffa

**Comment by dquadros** [comment]
This oddity (limitation?) comes straight from the textmode example in pico-playground.

**Comment by abaffa** [comment]
Hi Quadros, 
 no limitation... it was (weirdly) by design. Just changed #define COUNT 80 and it's ok. 

Btw, your RPTerm is 80 columns color capable, right? How did u manage the color limitation? did u use the pico-playground?
best,
Augusto Baffa

**Comment by mchobby** [comment]
Hi abaffa,
I did tested your github version, I read 80 charaters (just have to move a bit the horizontal alignment on my monitor).
Just look at the last line on the following picture (on SCM).
![Sélection_377](https://user-images.githubusercontent.com/2701466/206793770-a7117fbb-7da0-4104-8659-c5bcc222e7c6.jpg)

As a quick review, this seems to work nicely (no issue with WordStar) and NuPetScii still running properly.

Looks to be a great job. Thanks.

**Comment by dquadros** [comment]
RPTerm is based on picovga not the pico-playground example. Picovga uses a different hardware, with 8bit color, but the software is a more flexible and stable.

Enviado do Yahoo Mail no Android 
 
  Em sex., 9 9e dez. 9e 2022 às 21:43, Augusto ***@***.***> escreveu:   


Hi Quadros,
no limitation... it was (weirdly) by design. Just changed #define COUNT 80 and it's ok.

Btw, your RPTerm is 80 columns color capable, right? How did u manage the color limitation? did u use the pico-playground?
best,
Augusto Baffa

**Comment by mchobby** [comment]
> RPTerm is based on picovga not the pico-playground example. Picovga uses a different hardware, with 8bit color, but the software is a more flexible and stable. Enviado do Yahoo Mail no Android Em sex., 9 9e dez. 9e 2022 às 21:43, Augusto ***@***.***> escreveu: Hi Quadros, no limitation... it was (weirdly) by design. Just changed #define COUNT 80 and it's ok. Btw, your RPTerm is 80 columns color capable, right? How did u manage the color limitation? did u use the pico-playground? best, Augusto Baffa — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***>

I'd like the PicoVGA approach of RPTerm (I haved a look to it). Code is also cleaner at first sight. However hardware was more important for me since I'm using the RC2014 PicoTerm board. 
I must admit that having a color palette (like C64 color) for PicoTerm would be really great improvement.

**Comment by mchobby** [comment]
looks solved (with next merge)
