### ISSUE TITLE
Add CP437 charset / Other font support

### ISSUE THREAD

**Issue by mchobby** [RC2014Z80/picoterm#18]
Considering adding other font/charset to Picoterm.
See details about it on issue #17

**Comment by mchobby** [comment]
@abaffa 
I'm ready to implement the CP431 as you mentioned in the ticket (I have the font loader ready).
**However, I can't find information about CP431.** 
Did you means CP437 ? (refering to the Codepage 437 used in old DOS systems)

**Comment by abaffa** [comment]
Ops, yes I meant IBM code page 437.  It was used by DOS and other IBM PC compatible systems.

**Comment by mchobby** [comment]
That funny, I did also used that one from belgium with my old machine.

**Comment by abaffa** [comment]
Please, include "font.h" in next commit.

**Comment by mchobby** [comment]
Accordingly to `compiling.md` this is copied from the PICO SDK ;-)

**Comment by mchobby** [comment]
Implemented and uploaded

**Comment by mchobby** [comment]
@abaffa ,
This is the former implementation of the charset.
Some chars can still be tuned/improved for better display on screen).

You can easily inspect the charset with the SHIFT+CTRL+N shortcut.

Cheers,
Dominique

**Comment by abaffa** [comment]
> Accordingly to `compiling.md` this is copied from the PICO SDK ;-)

yep, but I was getting an error white compiling:

	CMakeFiles/picoterm.dir/main.c.obj: in function `select_graphic_font':
	main.c:(.text.select_graphic_font+0x24): undefined reference to `cp437_mono8'

because the original font.h don't have "extern const lv_font_t cp437_mono8;"

Also, compiling.md is missing in the repos.

**Comment by abaffa** [comment]
Just checked. These links are broken in readme.md (PicoTerm documentation)

* Using-NupetScii
* Compiling
* Add keyboard layout

**Comment by mchobby** [comment]
Will double check broken links

### Regarding font.h
cp437_mono8 is defined into cp437.c which is included into at compilation time with the CMakeList.txt
cp437.c uses definition from `font.h`.
I guest that compilation failed for cp437.c because of the missing/unresolved font.h... so "extern const lv_font_t cp437_mono8;" failed while linking main.c.

### Regarding compiling.md
Have moved into /docs (to avoids too much documentation file at github root).


### why not uploaded font.h ?
If later, it become out of sync with the library in the PICO_SDK (eg: type changed in implementation which is different from function declaration we had copied) then the software will HANG on the pico without any kind alert. I discovered it yesterday with a uint8_t vs int. No warning, no compilation error... but pico just hang at startup!

**Comment by abaffa** [comment]
I thought u edited font.h to include the cp437. You'ree totally right not to include the source.h.

I'm trying cp437 and it's great!!! Thanks for including it.

Also, your dec graphical set solution is much better than mine :D.  Congrats!

**Comment by mchobby** [comment]
Just fixed broken and uploaded changes.

### regarding font.h

I will check if CMakeList.txt can do the copy for us.
