### ISSUE TITLE
80 column version not working

### ISSUE THREAD

**Issue by dquadros** [RC2014Z80/picoterm#2]
There is a small bug in picoterm.c that will crash the program at startup: at the beginning of prepare_text_buffer() the for loop should be

`for(int c=0;c<ROWS;c++)`

instead if

`for(int c=0;c<=ROWS;c++)`

Also noticed that to build the program you will need to copy pico_sdk_import.cmake, pico_extras_import.cmake and fonts.h from pico-sdk, pico-extras and pico-playground\scanvideo\textmode.

**Comment by RFC2795** [comment]
Thank you. 

This has now been fixed for 0.1.3 of Picoterm.  I have also included your comments about the additional files needed to build this in to the ReadMe file so hopefully it will make things a bit easier for others.
