### ISSUE TITLE
Piezo Buzzer

### ISSUE THREAD

**Issue by mchobby** [RC2014Z80/picoterm#20]
Will use an **active** piezo buzzer (will be moved to I2C GPIO expander later).
See docs/picoterm-conn.md for details about material and pin assignation.

main.h now contains the declaration 
`#define BUZZER_GPIO 27 // active buzzer`

Follow the `USB_POWER_GPIO` as an example to initialize and manipulate the GPIO.

**Comment by abaffa** [comment]
As RP2040 has 3.3v GPIO level, its necessary few more components to give 5v to an active buzzer :)
![image](https://user-images.githubusercontent.com/7242662/209008681-965cb843-501c-4902-8418-aeae676618d8.png)

**Comment by mchobby** [comment]
The Active Piezo buzze available at Adafruit can also work at 3.3V

[Active Piezo Buzzer](https://www.adafruit.com/product/1536) @ Adafruit - indicating as working at 3.3V

**Comment by dquadros** [comment]
When I connect a buzzer to a microcontroller, I usually am more concerned with the current. I end up using a transistor even when it is not necessary.

**Comment by mchobby** [comment]
This indeed make sense. Additional transistor will cover any use-case.
Let's go for a 5V based active piezo.

**Comment by abaffa** [comment]
I'm late but that's it... and 5v buzzer generally is louder

**Comment by abaffa** [comment]
I've finished the bell 🔔. These are some (video) examples:

This is a charset test on normal and inverse modes. After finished each set I print a chr$(7) to request a bell sound.
[![Bell Example 1](https://img.youtube.com/vi/l8Ha7r8xiMk/0.jpg)](https://www.youtube.com/watch?v=l8Ha7r8xiMk)

For this another example, I'm using kermit to connect to a raspberry pi 3b (running raspian os). When typing backspace in the beginning of the sentence it sounds a bell:
[![Bell Example 2](https://img.youtube.com/vi/wgrPEbxIYTM/0.jpg)](https://www.youtube.com/watch?v=wgrPEbxIYTM)

The third one is running Ladder game: (I'm running on a Z180 at 18.432 mhz, so it's a little fast. And it was difficult to hold the mobile while recording and play it ...)
[![Bell Example 3](https://img.youtube.com/vi/jYn3Y0-AzDI/0.jpg)](https://www.youtube.com/watch?v=jYn3Y0-AzDI)

**Comment by mchobby** [comment]
Maybe should you have a look to the pushed code, I did made some changes/reorg into it.

**Comment by abaffa** [comment]
Yes, I'm waiting you to push all the new versions to merge and send it - thats why I havent commited it yet :)

**Comment by mchobby** [comment]
OK, CP437 should not take too much of the time... it is progressing surprisingly easy

**Comment by mchobby** [comment]
@abaffa 
Almost ready with the CP437 font ... minor thing to tune before final upload.

**Comment by mchobby** [comment]
The final CP437 code is not available on GitHub.
It is up to you to make the buzzer updates.
