### ISSUE TITLE
Decoupling picoterm.c / capturing un-resolved ESC sequence / capturing input stream

### ISSUE THREAD

**Issue by mchobby** [RC2014Z80/picoterm#26]
@abaffa ,
@RFC2795 ,
Hi guys,
I would like to share some thoughts with you for comments and remarks.
In the meanwhile, please, do not post changes over the version 1.5.2 right now.

### Decoupling Picoterm.C
I'm working intensively on the code of picoterm.c to decouple code in "logical section". 
The file picoterm.c is now really massive !

At this stage, here what I'm doing:
1. moving all HIGH LEVEL function about console drawing (print_string, read_key, clear_entire_screen, ...) to `picoterm_conio.c`
2. moving all screens (configuration screen, help screen, charset screen, ...) to `picoterm_screen.c`
3. should stays in `picoterm.c` the ESC sequence decoding stuff. I would be tempted to rename it `picoterm_core` as it will contains the CORE routines for running PicoTerm.

### Capture unresolved sequence
As additional features, I would like to capture the unresolved ESC sequence and send them to `picoterm_debug.c` .

### Capture input stream
I recently tried the game **hunt** under CP/M and it doesn't display very well under PicoTerm. 
The idea is to send a copy of the input stream to the `picoterm_debug.c`.
This way, it would be possible to make deeper analysis over the content.

**Comment by abaffa** [comment]
> That's an excellent idea! I'll be waiting your next versions :)

**Comment by mchobby** [comment]
@abaffa 
decoupling is finished. It is up to you.

I remove the "Capture Unresolved Sequence" because it ruined wordstar display.
I will reintroduced it as a separate issue.
