### ISSUE TITLE
keyboard repeat feature

### ISSUE THREAD

**Issue by mchobby** [RC2014Z80/picoterm#27]
Long pressing key on the keyboard should repeat the key.

delay before repeat and repeat delay should be stored into variables (to be configurable on later revision)

**Comment by dquadros** [comment]
Maybe you can get some ideas of how to implement the auto-repeat by looking at https://github.com/dquadros/RPTerm/blob/main/keybd.cpp

My implementation is a little crude, it is auto-repeating all keys. Also its is not checking if the modifiers (shift, control, alt) have changed.

**Comment by mchobby** [comment]
Looks to work properly.
Would be nice to be tested by someone else.
