### ISSUE TITLE
Licence for Picoterm - boring stuff but should be done

### ISSUE THREAD

**Issue by mchobby** [RC2014Z80/picoterm#28]
@RFC2795 ,
@feilipu ,

Sorry to bother you with such stuff but it would be the right time to append the License.txt file to the Picoterm repository.
As you are the 2 members of the RC2014Z80, I'm addressing you this ticket.
Picoterm involves lot of works and can have many versatile usages (not only for RC2014). Personnaly, I would be glad to use it togheter with my MicroPython boards.

The original Raspberry-Pi's project was published under the [**3-clause BSD**](https://opensource.org/licenses/BSD-3-Clause) .
I would suggest to keeps the same [3-clause BSD](https://opensource.org/licenses/BSD-3-Clause)  and "copyright" field should be completed.

Cheers,
Dominique

**Comment by RFC2795** [comment]
@mchobby 
Good point!

I have added the BSD 3-Clause licence. I think I've done it right, but if you can check and close this issue if it looks good to you.
Thanks
Spencer
