### ISSUE TITLE
Getting weird characters after changing terminal color

### ISSUE THREAD

**Issue by abaffa** [RC2014Z80/picoterm#32]
Hi, 
  this is an issue introduced after adding CP437 feature. To reproduce, use the following steps:

1. After boot (computer on prompt), type ctrl+shift+M
2. Change terminal color (I'm using 3 green - for example change to 0 white)
3. type esc (don't save)
4. after exit Picoterm menu, type enter - the terminal will show another prompt but with the letters swapped.

every string from computer will be swapped but ever typed will be correct.
I tested the serial baud option but that's not it.

After reset the picoterm (pushing the reset button) it backs to normal.

**Comment by mchobby** [comment]
Hi Abbafa,
I checked the last pushed code (this friday) and do not encounter any major issue.
I however noticed that under CP437 (being active) pressing the return key in the configuration screen displays an inverted "(" next to the question mark. That char is also reported to the main screen without issue for the RC2014 monitor. Pressing enter do normal RC2014 operation.

**Please note** that current version uses p & q for the ANSI font selection. A previous version did use a shortcut also implied in the parity selection (which broke the terminal communication) but I did quicly fix it.

Could you details your current options saved Flash ? used keyboard layout ?
Dominique

**Comment by abaffa** [comment]
Hi,
 reproducing again:

1) booting ...

![image](https://user-images.githubusercontent.com/7242662/211207410-0edc3d01-4913-44f6-97f4-23720ae64c8b.png)

2) my settings:
![image](https://user-images.githubusercontent.com/7242662/211207434-7597be0d-5348-4b8b-a0d1-7d55a15c0cf5.png)

3) changing settings: ( typed 3 - dark amber color)
![image](https://user-images.githubusercontent.com/7242662/211207442-5afa55a5-1022-4de0-bf08-11f4ea602788.png)

4) Exit settings menu (typed ESC) and typed enter or other keys... my typed keys are ok but the chars from CPU are swaped (note I tried to type backspace after typed "key(BSP)board".
![image](https://user-images.githubusercontent.com/7242662/211207530-ae02c29c-8c81-49c5-acca-6035f71ef6bf.png)

5) Clicked reset on Terminal board and did the same typing...
![image](https://user-images.githubusercontent.com/7242662/211207554-0d042908-ca85-46fa-b2f6-b66ddda75199.png)


I saved both "Charset" and "Ansi Graphic font" options, trying all combinations and repeated this test - the behavior is the same even starting from "NupetSCII" and "ASCII (7bits+reverse)".

**Comment by mchobby** [comment]
Are you really using Odd parity? (or is this a display artefac?)

Do you have something using 8N1 to repeat the test? (it is the major obvious difference between you and me).

**Comment by mchobby** [comment]
@abaffa 
I can't reproduce this issue even when stricly following your configuration ( I used Putty on a computer configured in 38400 bauds 8O1).

I posted a temporary build of Picoterm here:
http://df.mchobby.be/picoterm_1_5_3_temporary_build.zip 

Could you try that version? I would like to know if the issue could come from compiling process.

**Comment by mchobby** [comment]
Can still produce it. However, long time ago I fixed an use in the configuration screen where a key did altered two parameters (including the parity).
Don't hesitate to reopen if issue still persist.
Dominique
