### ISSUE TITLE
Any thoughts on adding support for AT/PS2 keyboards?

### ISSUE THREAD

**Issue by prosper00** [RC2014Z80/picoterm#34]
I have some cool retro keyboards that I'd like to use with a terminal. Any opinions on adding PS2 support to picoterm?

**Comment by mchobby** [comment]
Hi Proper,
We are planning to use the I2C bus on the expansion port (see issue #21). The code is ready... I'm currently putting my RC2014 into a case (raison for some delay).

Thanks to I2C bus, we could use a "[PS2 Keyboard Mouse I2C module](https://lonelybinary.com/products/ps2-keyboard-mouse-i2c-module)". It should not be too difficult to support it.

We could also create an "PS/2 to I2C" converter with a Super Cheap Raspberry-Pi Pico :-)

**Comment by mchobby** [comment]
It also exists the [SK5221 I2C encoder for Keyboard Matrix](https://www.sprintek.com/en/products/keyboard_ic/SK5221.aspx) (used when you want to create your own keyboard).

**Comment by prosper00** [comment]
Interesting... Thanks!

**Comment by mchobby** [comment]
After some additional reseach I did located several products converting "PS/2 Keyboard + PS/2 Mouse to USB".
So we can possibly use the Pico USB input with an PS/2 keyboard. Just needs to test it.
