### ISSUE TITLE
Changing the font seems to corrupt 8-bit characters

### ISSUE THREAD

**Issue by myount** [RC2014Z80/picoterm#39]
As mentioned in the discussion on #36, I built my own custom version of Picoterm to replace the font, because I'm really not fond of Ubuntu Mono.  As I said there, I used the [aspect-ratio-corrected OlivettiThin 8x16 font from int10h.org](https://int10h.org/oldschool-pc-fonts/fontlist/?2#olivetti) to replace the 7-bit ASCII characters, since it's a bit more period-appropriate (if not historically accurate) for a Z80 homebrew computer, and rebuilt the font file with `compile_font.py` to generate versions with the NuPETSCII and CP437 characters.

The 7-bit characters display fine in both normal and reverse video modes:

<details><summary>Image</summary>

![image](https://user-images.githubusercontent.com/637064/226493087-7f428a2c-c38c-48f8-b09c-a624e348b1cc.png)

</details>

But with either of the 8-bit character sets enabled, the 8-bit characters are corrupted:

<details><summary>Image</summary>

![image](https://user-images.githubusercontent.com/637064/226493219-94949d28-3923-4a58-b37d-5cbe9c692e85.png)

If I recall correctly, this screenshot is of the NuPETSCII character set.  CP437 is similarly, but not identically, corrupted.

</details>

(These captures are via an OSSC and Elgato HDMI capture card.  Forgive the poor quality; I'm using a cheap, unshielded VGA cable.)

As I mentioned in #36, I used the LVGL converter linked in the comments at the top of the existing font files; [`olivettithin_8x16.c`](https://github.com/RC2014Z80/picoterm/files/11024012/olivettithin_8x16.c.txt) was the resulting file; I copied the glyph definitions over the top of the ones in `font8.c`, resulting in [this](https://github.com/RC2014Z80/picoterm/files/11024024/font8.c.txt), and `compile_font.py` gave me [this `nupetscii.c`](https://github.com/RC2014Z80/picoterm/files/11024025/nupetscii.c.txt) and [this `cp437.c`](https://github.com/RC2014Z80/picoterm/files/11024026/cp437.c.txt).

I know I went about replacing the font in a pretty hamfisted way, because C is not my strong suit and I just wanted to get a feel for how much of an undertaking replacing the font would be.  Seems it may be more difficult than I was hoping.  I guess OlivettiThin 8x16's glyphs being different sizes probably messed up memory offsets for the 8-bit characters.  It does have [its own CP437 characters](https://int10h.org/oldschool-pc-fonts/fontlist/font?olivettithin_8x16), but I didn't try using those since I'm not entirely certain they would be at the codepoints that Picoterm expects.  Although having said all this, I'm also perfectly content not to use any 8-bit characters in Picoterm...

**Comment by mchobby** [comment]
@myount 
I'm currently working on including several fonts into the PicoTerm (starting with OlivettiThin8x16, based on your comment in #36 ).
Some adjustement will be necessary on font `.data` in font-suite but the results are quite acceptable.
I will publish an alpha version shortly.

**Comment by mchobby** [comment]
Version 1.5.3-alpha released, just check the 

https://github.com/RC2014Z80/picoterm/tree/main/80col-mono/Build/1.5.3-alpha
