### ISSUE TITLE
Keyboard layout support for Swedish (and more)

### ISSUE THREAD

**Issue by MrSVCD** [RC2014Z80/picoterm#4]
I would like support for Swedish keyboard layout.

While there is no need for support of ÅÄÖ since the target computers don't know what they are.
The problem are special characters like *-/ are in different places (it has been a pain to use a UK keyboard layout when I am used to a SE keyboard layout for this reason).

I could not see where I could change this in the code so no pull request but a issue. My inexperience is showing here.

**Comment by dquadros** [comment]
Not sure if this will help you, but in my fork at https://github.com/dquadros/picoterm I've added support to the Brazilian keyboard (expanding on Birko Bergt fork) for  the 80 column version. This is done by changing keycode_to_ascii.h, to do that you need to know the usb codes for the keys. I've also cleaned the code a little and added more comments, hope that helps understanding it.

**Comment by RFC2795** [comment]
Thank you dquadros
