### ISSUE TITLE
tusb_config.h

### ISSUE THREAD

**Issue by ExtremeElectronics** [RC2014Z80/picoterm#42]
Might be my build environment, 
but I needed to make a copy of [tusb_config.h](https://github.com/RC2014Z80/picoterm/blob/main/common/tusb_config.h) into the  80col-mono directory before I could successfully build.

No problems, but it might help someone else.

**Comment by mchobby** [comment]
Hi,
If you look here 
https://github.com/RC2014Z80/picoterm/tree/main/80col-mono
the repository shows **a link** to tusb_config.h .

This as probably not be applied/restored on your target system.
Copying the file from ../common/tusb_config.h 

Regards,
Dominique
