### ISSUE TITLE
Not all USB keyboards currently works (workaround)

### ISSUE THREAD

**Issue by abaffa** [RC2014Z80/picoterm#43]
Last week I received a wrong Dierya Keyboard DK61SE and noticed that it wasnt working with picoterm. I currently use a DK63 keyboard that works perfectly and I couldn't immediately understand why the DK61SE wouldn't work.

After some debugging I realized that, for some strange reason, keybd.c/tinyUSB detects a keyboard and mouse. The problem is that when the mouse is detected, it overwrites the keybd_dev_addr with the new device and we are left without communication with the keyboard. I tried a little workaround and it worked. I believe this must be the same problem with other keyboards

In the callback "tuh_hid_mount_cb", I added an "else" to avoid calling the  function "tuh_hid_receive_report", if anything other than a keyboard is detected. My function looked like this:

```
void tuh_hid_mount_cb(uint8_t dev_addr, uint8_t instance, uint8_t const* desc_report, uint16_t desc_len) {
	sprintf( debug_msg, "HID device address = %d, instance = %d is mounted", dev_addr, instance );
	debug_print( debug_msg );

	// Interface protocol (hid_interface_protocol_enum_t)
	const char* protocol_str[] = { "None", "Keyboard", "Mouse" };
	uint8_t const itf_protocol = tuh_hid_interface_protocol(dev_addr, instance);
	sprintf( debug_msg, "HID Interface Protocol = %s", protocol_str[itf_protocol] );
	debug_print( debug_msg );

	if( itf_protocol == 1 ) // Did we attached a keyboard?
		keybd_dev_addr = dev_addr;
	else  
		return; // just ignore other devices than keyboard <<<<<<<<<<<<<<<<<<<<<<
 ...
```

It would be good to test it with other keyboards that had compatibility issues. I also don't believe that picoterm should support a mouse or other device at the moment, so other devices may be ignored.

**Comment by mchobby** [comment]
Integrated in source code.
It looks obvious to pump the message from the keyboard, not from the mouse
