### ISSUE TITLE
Not supporting Raspberry-Pi official Keyboard

### ISSUE THREAD

**Issue by mchobby** [RC2014Z80/picoterm#5]
Raspberry-Pi official Keyboards are small, inexpensive and very comfortable to use.
So they would be a nice addition to RC2014 setup but it doesn't works.

The keyboard also includes USB HUB and I think this is causing compatibility issue.

Symptom: When plugin the Keyboard on the Pico, the PicoTerm output do show/hide/show then become completely black.

**Comment by RFC2795** [comment]
Latest revisions support the excellent RPi keyboards. And, hopefully, almost all regular USB keyboards.
