### ISSUE TITLE
USB instabilities when compiling v0.1.3 - wanted to support FR/BE layout (Azerty)

### ISSUE THREAD

**Issue by mchobby** [RC2014Z80/picoterm#6]
Hi,
I did tried to compile the v0.1.3 to make required changes to support AZERTY layout.
I'm getting lot of instabilities when connecting keyboard whereas the provided UF2 is quite stable.

So, I do wonder about the state of source code on the repository.
Are the source files up to date?
Dominique

**Comment by RFC2795** [comment]
Hi Dominique,

Sorry, sync had been lost between the source and build files. Both have now been updated and should contain everything you need to build stable AZERTY .uf2 file now.

Spencer
