### ISSUE TITLE
1.1 source 80 column version not working - Bug reintroduced ?

### ISSUE THREAD

**Issue by DonaldMoran** [RC2014Z80/picoterm#7]
Hello,

With the latest 1.1 source, an older and Closed bug "80 column version not working #2" by "dquadros" seems to have been re-introduced.

"There is a small bug in picoterm.c that will crash the program at startup: at the beginning of prepare_text_buffer() the for loop should be" << dquadros

for(int c=0;c<ROWS;c++)

instead if

for(int c=0;c<=ROWS;c++)

Built from source, the 80 column one did not run until making this update.

Thanks

**Comment by mchobby** [comment]
Thanks!
This was indeed the issue I noticed and the fix!

**Comment by RFC2795** [comment]
Thank you, this does seem to have fixed it.
